// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Audio$QueerLoop from "./Audio.bs.js";

function setupSingleDelay(audioContext, sourceNode, output, $staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, param) {
  var gain = $staropt$star !== undefined ? $staropt$star : 0.7;
  var outputGain = $staropt$star$1 !== undefined ? $staropt$star$1 : 0.5;
  var cutoff = $staropt$star$2 !== undefined ? $staropt$star$2 : 2000.0;
  var midiNote = $staropt$star$3 !== undefined ? $staropt$star$3 : 45.0;
  var now = audioContext.currentTime;
  var delayNode = audioContext.createDelay(1.0);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  var gainNode = audioContext.createGain();
  var localGainNode = audioContext.createGain();
  var delayOffset = 128.0 / audioContext.sampleRate;
  var delayPeriod = 1.0 / Audio$QueerLoop.noteToFrequency(midiNote) - delayOffset;
  console.log(delayPeriod);
  gainNode.gain.setValueAtTime(gain, now);
  delayNode.delayTime.setValueAtTime(delayPeriod, now);
  localGainNode.gain.setValueAtTime(outputGain, now);
  sourceNode.connect(delayNode);
  delayNode.connect(biquadFilter);
  biquadFilter.connect(gainNode);
  gainNode.connect(delayNode);
  gainNode.connect(localGainNode);
  localGainNode.connect(output);
  return /* record */[
          /* delayNode */delayNode,
          /* biquadFilter */biquadFilter,
          /* gainNode */gainNode
        ];
}

function setupDelaysFeedback(audioContext, sourceNode, output, $staropt$star, $staropt$star$1, $staropt$star$2, param) {
  var gain = $staropt$star !== undefined ? $staropt$star : 0.7;
  var cutoff = $staropt$star$1 !== undefined ? $staropt$star$1 : 2000.0;
  var midiNotes = $staropt$star$2 !== undefined ? $staropt$star$2 : /* array */[
      45.0,
      52.0
    ];
  var now = audioContext.currentTime;
  var masterGainNode = audioContext.createGain();
  var masterDelayNode = audioContext.createDelay(0.5);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  masterDelayNode.delayTime.setValueAtTime(0.5, now);
  masterGainNode.gain.setValueAtTime(0.5, now);
  var delayOutputGain = 1.0 / midiNotes.length;
  $$Array.map((function (midiNote) {
          var partial_arg = midiNote;
          var partial_arg$1 = cutoff;
          var partial_arg$2 = delayOutputGain;
          var partial_arg$3 = gain;
          return (function (param) {
              return setupSingleDelay(audioContext, masterDelayNode, masterGainNode, partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param);
            });
        }), midiNotes);
  sourceNode.connect(masterDelayNode);
  masterGainNode.connect(output);
  return /* record */[
          /* delayNode */masterDelayNode,
          /* biquadFilter */biquadFilter,
          /* gainNode */masterGainNode
        ];
}

function setupDelays(audioContext, sourceNode, output, $staropt$star, $staropt$star$1, $staropt$star$2, param) {
  var gain = $staropt$star !== undefined ? $staropt$star : 0.7;
  var cutoff = $staropt$star$1 !== undefined ? $staropt$star$1 : 2000.0;
  var midiNotes = $staropt$star$2 !== undefined ? $staropt$star$2 : /* array */[
      45.0,
      62.0,
      69.0,
      73.0
    ];
  var now = audioContext.currentTime;
  var masterGainNode = audioContext.createGain();
  var masterDelayNode = audioContext.createDelay(0.5);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  masterDelayNode.delayTime.setValueAtTime(0.5, now);
  masterGainNode.gain.setValueAtTime(0.5, now);
  var delayOutputGain = 1.0 / midiNotes.length;
  $$Array.map((function (midiNote) {
          var partial_arg = midiNote;
          var partial_arg$1 = cutoff;
          var partial_arg$2 = delayOutputGain;
          var partial_arg$3 = gain;
          return (function (param) {
              return setupSingleDelay(audioContext, masterDelayNode, masterGainNode, partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param);
            });
        }), midiNotes);
  sourceNode.connect(masterDelayNode);
  masterGainNode.connect(output);
  return /* record */[
          /* delayNode */masterDelayNode,
          /* biquadFilter */biquadFilter,
          /* gainNode */masterGainNode
        ];
}

export {
  setupSingleDelay ,
  setupDelaysFeedback ,
  setupDelays ,
  
}
/* Audio-QueerLoop Not a pure module */
