// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Audio$QueerLoop from "./Audio.bs.js";

function setupSingleDelay(audioContext, sourceNode, output, gainOpt, outputGainOpt, cutoffOpt, midiNoteOpt, param) {
  var gain = gainOpt !== undefined ? gainOpt : 0.7;
  var outputGain = outputGainOpt !== undefined ? outputGainOpt : 0.5;
  var cutoff = cutoffOpt !== undefined ? cutoffOpt : 2000.0;
  var midiNote = midiNoteOpt !== undefined ? midiNoteOpt : 45.0;
  var now = audioContext.currentTime;
  var delayNode = audioContext.createDelay(1.0);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  var gainNode = audioContext.createGain();
  var localGainNode = audioContext.createGain();
  var delayOffset = 128.0 / audioContext.sampleRate;
  var delayPeriod = 1.0 / Audio$QueerLoop.noteToFrequency(midiNote) - delayOffset;
  console.log(delayPeriod);
  gainNode.gain.setValueAtTime(gain, now);
  delayNode.delayTime.setValueAtTime(delayPeriod, now);
  localGainNode.gain.setValueAtTime(outputGain, now);
  sourceNode.connect(delayNode);
  delayNode.connect(biquadFilter);
  biquadFilter.connect(gainNode);
  gainNode.connect(delayNode);
  gainNode.connect(localGainNode);
  localGainNode.connect(output);
  return {
          delayNode: delayNode,
          biquadFilter: biquadFilter,
          gainNode: gainNode
        };
}

function setupDelaysFeedback(audioContext, sourceNode, output, gainOpt, cutoffOpt, midiNotesOpt, param) {
  var gain = gainOpt !== undefined ? gainOpt : 0.7;
  var cutoff = cutoffOpt !== undefined ? cutoffOpt : 2000.0;
  var midiNotes = midiNotesOpt !== undefined ? midiNotesOpt : [
      45.0,
      52.0
    ];
  var now = audioContext.currentTime;
  var masterGainNode = audioContext.createGain();
  var masterDelayNode = audioContext.createDelay(0.5);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  masterDelayNode.delayTime.setValueAtTime(0.5, now);
  masterGainNode.gain.setValueAtTime(0.5, now);
  var delayOutputGain = 1.0 / midiNotes.length;
  $$Array.map((function (midiNote) {
          var partial_arg = midiNote;
          var partial_arg$1 = cutoff;
          var partial_arg$2 = delayOutputGain;
          var partial_arg$3 = gain;
          return (function (param) {
              return setupSingleDelay(audioContext, masterDelayNode, masterGainNode, partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param);
            });
        }), midiNotes);
  sourceNode.connect(masterDelayNode);
  masterGainNode.connect(output);
  return {
          delayNode: masterDelayNode,
          biquadFilter: biquadFilter,
          gainNode: masterGainNode
        };
}

function setupDelays(audioContext, sourceNode, output, gainOpt, cutoffOpt, midiNotesOpt, param) {
  var gain = gainOpt !== undefined ? gainOpt : 0.7;
  var cutoff = cutoffOpt !== undefined ? cutoffOpt : 2000.0;
  var midiNotes = midiNotesOpt !== undefined ? midiNotesOpt : [
      45.0,
      62.0,
      69.0,
      73.0
    ];
  var now = audioContext.currentTime;
  var masterGainNode = audioContext.createGain();
  var masterDelayNode = audioContext.createDelay(0.5);
  var biquadFilter = Audio$QueerLoop.makeFilter(audioContext, /* LowPass */Block.__(0, [
          cutoff,
          0.0
        ]));
  masterDelayNode.delayTime.setValueAtTime(0.5, now);
  masterGainNode.gain.setValueAtTime(0.5, now);
  var delayOutputGain = 1.0 / midiNotes.length;
  $$Array.map((function (midiNote) {
          var partial_arg = midiNote;
          var partial_arg$1 = cutoff;
          var partial_arg$2 = delayOutputGain;
          var partial_arg$3 = gain;
          return (function (param) {
              return setupSingleDelay(audioContext, masterDelayNode, masterGainNode, partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param);
            });
        }), midiNotes);
  sourceNode.connect(masterDelayNode);
  masterGainNode.connect(output);
  return {
          delayNode: masterDelayNode,
          biquadFilter: biquadFilter,
          gainNode: masterGainNode
        };
}

export {
  setupSingleDelay ,
  setupDelaysFeedback ,
  setupDelays ,
  
}
/* Audio-QueerLoop Not a pure module */
