// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


function toArrayBuffer (blob){
     return new Promise((resolve, reject) => {
     const reader = new FileReader();
     reader.addEventListener('loadend', (e) => {
     resolve(reader.result);
     });
     reader.addEventListener('error', reject);
     reader.readAsArrayBuffer(blob);
     });
     };

export {
  toArrayBuffer ,
  
}
/* No side effect */
