// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function toArrayBuffer (blob){
     return new Promise((resolve, reject) => {
     const reader = new FileReader();
     reader.addEventListener('loadend', (e) => {
     resolve(reader.result);
     });
     reader.addEventListener('error', reject);
     reader.readAsArrayBuffer(blob);
     });
     };

exports.toArrayBuffer = toArrayBuffer;
/* No side effect */
