// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Ctx = { };

function invert(canvas) {
  var ctx = canvas.getContext("2d");
  var w = canvas.width;
  var h = canvas.height;
  var originalCompositeOperation = ctx.globalCompositeOperation;
  ctx.globalCompositeOperation = "difference";
  ctx.fillStyle = "#FFFFFF";
  ctx.fillRect(0, 0, w, h);
  ctx.globalCompositeOperation = originalCompositeOperation;
  
}

exports.Ctx = Ctx;
exports.invert = invert;
/* No side effect */
