// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var JsQr$QueerLoop = require("./JsQr.bs.js");

self.onmessage = (function (e) {
    var match = e.data;
    var maybeCode = JsQr$QueerLoop.jsQR(match[0], match[1], match[2]);
    postMessage(maybeCode);
    return /* () */0;
  });

/*  Not a pure module */
