// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Instascan = require("instascan");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Instascan$QueerLoop = require("./Instascan.bs.js");

var videoEl = document.querySelector("video");

var videoEl$1 = (videoEl == null) ? undefined : Caml_option.some(videoEl);

var instascanOpts = {
  video: Js_null_undefined.fromOption(videoEl$1)
};

var scanner = new Instascan.Scanner(instascanOpts);

Curry._1(Instascan$QueerLoop.Camera[/* getCameras */0], /* () */0).then((function (cameras) {
          if (cameras.length !== 0) {
            scanner.start(Caml_array.caml_array_get(cameras, 0));
          } else {
            console.error("No cameras found!");
          }
          return Promise.resolve(/* () */0);
        })).catch((function (err) {
        console.error("getCameras failed", err);
        return Promise.resolve(/* () */0);
      }));

exports.videoEl = videoEl$1;
exports.instascanOpts = instascanOpts;
exports.scanner = scanner;
/* videoEl Not a pure module */
