// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Instascan = require("instascan");

var partial_arg = Instascan.Camera;

function getCameras(param) {
  return partial_arg.getCameras();
}

var Camera = /* module */[/* getCameras */getCameras];

var Scanner = /* module */[];

exports.Camera = Camera;
exports.Scanner = Scanner;
/* partial_arg Not a pure module */
