// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Jsqr = require("jsqr");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function jsQR(d, w, h) {
  return Caml_option.nullable_to_opt(Jsqr(d, w, h));
}

exports.jsQR = jsQR;
/* jsqr Not a pure module */
