// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


var defaultOptions_012 = /* cameraIndices : array */[0];

var defaultOptions = /* record */[
  /* background */"",
  /* includeDomain */true,
  /* includeQueryString */true,
  /* includeHash */true,
  /* invert */false,
  /* animate */false,
  /* opacity */0.1,
  /* title */undefined,
  /* url */undefined,
  /* poem */undefined,
  /* wiki */undefined,
  /* youtubeVideo */undefined,
  defaultOptions_012
];

var currentOptions = /* record */[/* contents */defaultOptions];

export {
  defaultOptions ,
  currentOptions ,
  
}
/* No side effect */
