// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var defaultOptions_cameraIndices = [0];

var defaultOptions = {
  background: "",
  includeDomain: true,
  includeQueryString: true,
  includeHash: true,
  invert: false,
  animate: false,
  opacity: 0.1,
  title: undefined,
  url: undefined,
  poem: undefined,
  wiki: undefined,
  youtubeVideo: undefined,
  cameraIndices: defaultOptions_cameraIndices
};

var currentOptions = {
  contents: defaultOptions
};

export {
  defaultOptions ,
  currentOptions ,
  
}
/* No side effect */
