// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as Qrcodegen from "./qrcodegen";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

var low = Qrcodegen.Ecc.LOW;

var medium = Qrcodegen.Ecc.MEDIUM;

var quartile = Qrcodegen.Ecc.QUARTILE;

var high = Qrcodegen.Ecc.HIGH;

var Ecc = /* module */[
  /* low */low,
  /* medium */medium,
  /* quartile */quartile,
  /* high */high
];

function _encodeText(prim, prim$1) {
  return Qrcodegen.encodeText(prim, prim$1);
}

function encodeText(text, ecc) {
  var exit = 0;
  var code;
  try {
    code = Qrcodegen.encodeText(text, ecc);
    exit = 1;
  }
  catch (exn){
    return undefined;
  }
  if (exit === 1) {
    return Caml_option.some(code);
  }
  
}

var QrCode = /* module */[
  /* _encodeText */_encodeText,
  /* encodeText */encodeText
];

function _setSvg (t,el){
     el.src = "data:image/svg+xml;utf8," + encodeURIComponent(t);
     };

function setSvg(t, el) {
  return _setSvg(t.toSvgString(4), el);
}

export {
  Ecc ,
  QrCode ,
  _setSvg ,
  setSvg ,
  
}
/* low Not a pure module */
