// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Qrcodegen = require("./qrcodegen");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var ecc = Qrcodegen.Ecc;

var low = ecc.LOW;

var medium = ecc.MEDIUM;

var quartile = ecc.QUARTILE;

var high = ecc.HIGH;

var Ecc = {
  ecc: ecc,
  low: low,
  medium: medium,
  quartile: quartile,
  high: high
};

function _encodeText(prim, prim$1) {
  return Qrcodegen.encodeText(prim, prim$1);
}

function encodeText(text, ecc) {
  var code;
  try {
    code = Qrcodegen.encodeText(text, ecc);
  }
  catch (exn){
    return ;
  }
  return Caml_option.some(code);
}

var QrCode = {
  _encodeText: _encodeText,
  encodeText: encodeText
};

function _setSvg (t,el){
     el.src = "data:image/svg+xml;utf8," + encodeURIComponent(t);
     };

function setSvg(t, el) {
  return _setSvg(t.toSvgString(4), el);
}

exports.Ecc = Ecc;
exports.QrCode = QrCode;
exports._setSvg = _setSvg;
exports.setSvg = setSvg;
/* ecc Not a pure module */
