// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Util$QueerLoop = require("./Util.bs.js");
var UserMedia$QueerLoop = require("./UserMedia.bs.js");

function scanUsingDeviceId(videoEl, deviceId, scanCallback) {
  return UserMedia$QueerLoop.initStreamByDeviceId(videoEl, deviceId).then((function (video) {
                var canvas = document.createElement("canvas");
                Util$QueerLoop.withQuerySelector("body", (function (body) {
                        body.appendChild(canvas);
                        return /* () */0;
                      }));
                var worker = new Worker("worker.js");
                var msgBackHandler = function (e) {
                  var maybeCode = e.data;
                  if (maybeCode !== undefined) {
                    Curry._1(scanCallback, Caml_option.valFromOption(maybeCode).data);
                  }
                  return /* () */0;
                };
                worker.onmessage = msgBackHandler;
                var frameCount = /* record */[/* contents */0];
                var onTick = function (param) {
                  if (video.readyState === 4) {
                    var width = video.videoWidth;
                    var height = video.videoHeight;
                    if (canvas.width !== width) {
                      canvas.width = width;
                      canvas.height = height;
                    }
                    if (frameCount[0] % 5 === 0) {
                      var ctx = canvas.getContext("2d");
                      ctx.drawImage(video, 0, 0);
                      var imageData = ctx.getImageData(0, 0, width, height);
                      worker.postMessage(/* tuple */[
                            imageData.data,
                            width,
                            height
                          ]);
                    }
                    
                  }
                  frameCount[0] = frameCount[0] + 1 | 0;
                  requestAnimationFrame(onTick);
                  return /* () */0;
                };
                requestAnimationFrame(onTick);
                return Promise.resolve(canvas);
              }));
}

exports.scanUsingDeviceId = scanUsingDeviceId;
/* Util-QueerLoop Not a pure module */
