// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


var defaultHmac = {
  name: "HMAC",
  hash: "SHA-256"
};

function exportKeyJWK(key) {
  return window.crypto.subtle.exportKey("jwk", key).then((function (t) {
                return Promise.resolve(JSON.stringify(t));
              }));
}

function importKeyJWK(json) {
  var parsed = JSON.parse(json);
  return window.crypto.subtle.importKey("jwk", parsed, defaultHmac, true, /* array */[
              "sign",
              "verify"
            ]);
}

function generateHmac(param) {
  return window.crypto.subtle.generateKey(defaultHmac, true, /* array */[
              "sign",
              "verify"
            ]);
}

var defaultHmacKeyJSON = "{\"alg\":\"HS256\",\"ext\":true,\"k\":\"A-cS_q7opsDHm5vusaNtzSbaJcI153rl-2VVPXyliu2G5nKicquFkf-rcFNCyQkC50CDjzFdDhIh9WzzWSXXHw\",\"key_ops\":[\"sign\",\"verify\"],\"kty\":\"oct\"}";

var defaultHmacKey = importKeyJWK(defaultHmacKeyJSON);

export {
  defaultHmac ,
  exportKeyJWK ,
  importKeyJWK ,
  generateHmac ,
  defaultHmacKeyJSON ,
  defaultHmacKey ,
  
}
/* defaultHmacKey Not a pure module */
