// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");
var Util$QueerLoop = require("./Util.bs.js");

function setAnimacy(svg, hash) {
  Util$QueerLoop.withQuerySelectorAllFrom(".animate", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code previous");
                        
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".previous", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".selected", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        
                      }), param);
        }));
  return Belt_Option.map(Caml_option.nullable_to_opt(svg.querySelector("#code" + hash)), (function (toAnimate) {
                toAnimate.setAttribute("class", "code animate");
                
              }));
}

function setSelection(svg, hash) {
  Util$QueerLoop.withQuerySelectorAllFrom(".animate", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".previous", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".selected", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        
                      }), param);
        }));
  return Belt_Option.map(Caml_option.nullable_to_opt(svg.querySelector("#code" + hash)), (function (toAnimate) {
                toAnimate.setAttribute("class", "code selected");
                
              }));
}

function modifyClassSet(f, el) {
  var s = el.getAttribute("class");
  var newSet = (s == null) ? Curry._1(f, undefined) : Curry._1(f, Belt_SetString.fromArray(s.split(" ")));
  el.setAttribute("class", Belt_SetString.toArray(newSet).join(" "));
  
}

function getClassesSvg(el) {
  var s = el.getAttribute("class");
  if (!(s == null)) {
    return Belt_SetString.fromArray(s.split(" "));
  }
  
}

function addClassSvg(el, classNameToAdd) {
  return modifyClassSet((function (s) {
                return Belt_SetString.add(s, classNameToAdd);
              }), el);
}

function removeClassSvg(el, classNameToRemove) {
  return modifyClassSet((function (s) {
                return Belt_SetString.remove(s, classNameToRemove);
              }), el);
}

function toggleClassSvg(el, classNameToToggle) {
  return modifyClassSet((function (s) {
                if (Belt_SetString.has(s, classNameToToggle)) {
                  return Belt_SetString.remove(s, classNameToToggle);
                } else {
                  return Belt_SetString.add(s, classNameToToggle);
                }
              }), el);
}

function toggleHash(hash) {
  Util$QueerLoop.withQuerySelectorDom("#code" + hash, (function (code) {
          return toggleClassSvg(code, "active");
        }));
  var result = Belt_Array.some(Util$QueerLoop.withQuerySelectorAll(".code" + hash, (function (param) {
              return $$Array.map((function (link) {
                            var linkClasses = link.classList;
                            return linkClasses.toggle("active");
                          }), param);
            })), (function (x) {
          return x;
        }));
  Util$QueerLoop.withQuerySelectorAll(".active", (function (a) {
          Util$QueerLoop.withQuerySelectorDom(".code.animate", (function (code) {
                  if (!Belt_SetString.has(getClassesSvg(code), "active")) {
                    if (a.length !== 0) {
                      return addClassSvg(code, "temporarilyInactive");
                    } else {
                      return removeClassSvg(code, "temporarilyInactive");
                    }
                  }
                  
                }));
          
        }));
  return result;
}

exports.setAnimacy = setAnimacy;
exports.setSelection = setSelection;
exports.modifyClassSet = modifyClassSet;
exports.getClassesSvg = getClassesSvg;
exports.addClassSvg = addClassSvg;
exports.removeClassSvg = removeClassSvg;
exports.toggleClassSvg = toggleClassSvg;
exports.toggleHash = toggleHash;
/* Util-QueerLoop Not a pure module */
