// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Belt_Array from "../node_modules/bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "../node_modules/bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";
import * as Belt_SetString from "../node_modules/bs-platform/lib/es6/belt_SetString.js";
import * as Util$QueerLoop from "./Util.bs.js";

function setAnimacy(svg, hash) {
  Util$QueerLoop.withQuerySelectorAllFrom(".animate", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code previous");
                        return /* () */0;
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".previous", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        return /* () */0;
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".selected", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        return /* () */0;
                      }), param);
        }));
  return Belt_Option.map(Caml_option.nullable_to_opt(svg.querySelector("#code" + hash)), (function (toAnimate) {
                toAnimate.setAttribute("class", "code animate");
                return /* () */0;
              }));
}

function setSelection(svg, hash) {
  Util$QueerLoop.withQuerySelectorAllFrom(".animate", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        return /* () */0;
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".previous", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        return /* () */0;
                      }), param);
        }));
  Util$QueerLoop.withQuerySelectorAllFrom(".selected", svg, (function (param) {
          return $$Array.map((function (animated) {
                        animated.setAttribute("class", "code");
                        return /* () */0;
                      }), param);
        }));
  return Belt_Option.map(Caml_option.nullable_to_opt(svg.querySelector("#code" + hash)), (function (toAnimate) {
                toAnimate.setAttribute("class", "code selected");
                return /* () */0;
              }));
}

function modifyClassSet(f, el) {
  var match = el.getAttribute("class");
  var newSet = (match == null) ? Curry._1(f, Belt_SetString.empty) : Curry._1(f, Belt_SetString.fromArray(match.split(" ")));
  el.setAttribute("class", Belt_SetString.toArray(newSet).join(" "));
  return /* () */0;
}

function getClassesSvg(el) {
  var match = el.getAttribute("class");
  if (match == null) {
    return Belt_SetString.empty;
  } else {
    return Belt_SetString.fromArray(match.split(" "));
  }
}

function addClassSvg(el, classNameToAdd) {
  return modifyClassSet((function (s) {
                return Belt_SetString.add(s, classNameToAdd);
              }), el);
}

function removeClassSvg(el, classNameToRemove) {
  return modifyClassSet((function (s) {
                return Belt_SetString.remove(s, classNameToRemove);
              }), el);
}

function toggleClassSvg(el, classNameToToggle) {
  return modifyClassSet((function (s) {
                if (Belt_SetString.has(s, classNameToToggle)) {
                  return Belt_SetString.remove(s, classNameToToggle);
                } else {
                  return Belt_SetString.add(s, classNameToToggle);
                }
              }), el);
}

function toggleHash(hash) {
  Util$QueerLoop.withQuerySelectorDom("#code" + hash, (function (code) {
          return toggleClassSvg(code, "active");
        }));
  var result = Belt_Array.some(Util$QueerLoop.withQuerySelectorAll(".code" + hash, (function (param) {
              return $$Array.map((function (link) {
                            var linkClasses = link.classList;
                            return linkClasses.toggle("active");
                          }), param);
            })), (function (x) {
          return x;
        }));
  Util$QueerLoop.withQuerySelectorAll(".active", (function (a) {
          Util$QueerLoop.withQuerySelectorDom(".code.animate", (function (code) {
                  if (Belt_SetString.has(getClassesSvg(code), "active")) {
                    return 0;
                  } else if (a.length !== 0) {
                    return addClassSvg(code, "temporarilyInactive");
                  } else {
                    return removeClassSvg(code, "temporarilyInactive");
                  }
                }));
          return /* () */0;
        }));
  return result;
}

export {
  setAnimacy ,
  setSelection ,
  modifyClassSet ,
  getClassesSvg ,
  addClassSvg ,
  removeClassSvg ,
  toggleClassSvg ,
  toggleHash ,
  
}
/* Util-QueerLoop Not a pure module */
