// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "../node_modules/bs-platform/lib/es6/caml_js_exceptions.js";

function serializeTime(date) {
  return date.getTime().toString();
}

function deserializeTime(str) {
  var date = new Date();
  date.setTime(Number(str));
  return date;
}

function maybeDeserializeTime(str) {
  var t = Number(str);
  if (isFinite(t)) {
    var date = new Date();
    date.setTime(t);
    var exit = 0;
    var val;
    try {
      val = date.toISOString();
      exit = 1;
    }
    catch (raw_err){
      var err = Caml_js_exceptions.internalToOCamlException(raw_err);
      console.error("Could not make valid date from:", t, err);
      return undefined;
    }
    if (exit === 1) {
      return Caml_option.some(date);
    }
    
  }
  
}

function getTimestamp(param) {
  var date = new Date();
  return date.getTime().toString();
}

function getTimestampAndLocaleString(param) {
  var date = new Date();
  return /* tuple */[
          date.getTime().toString(),
          date.toLocaleString()
        ];
}

export {
  serializeTime ,
  deserializeTime ,
  maybeDeserializeTime ,
  getTimestamp ,
  getTimestampAndLocaleString ,
  
}
/* No side effect */
