// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as ElementRe from "../node_modules/bs-webapi/src/dom/nodes/ElementRe.js";
import * as Belt_Array from "../node_modules/bs-platform/lib/es6/belt_Array.js";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

function getCameras(param) {
  return window.navigator.mediaDevices.enumerateDevices().then((function (devices) {
                return Promise.resolve(Belt_Array.keep(devices, (function (x) {
                                  return x.kind === "videoinput";
                                })));
              }));
}

function getAudioStream(param) {
  return window.navigator.mediaDevices.getUserMedia({
              audio: true
            });
}

function initStreamByDeviceId(videoEl, deviceId) {
  return window.navigator.mediaDevices.getUserMedia({
                video: {
                  deviceId: deviceId
                }
              }).then((function (stream) {
                videoEl.srcObject = stream;
                var match = ElementRe.asHtmlElement(videoEl);
                if (match !== undefined) {
                  Caml_option.valFromOption(match).setAttribute("playsinline", "true");
                }
                videoEl.play();
                return Promise.resolve(videoEl);
              }));
}

export {
  getCameras ,
  getAudioStream ,
  initStreamByDeviceId ,
  
}
/* ElementRe Not a pure module */
