// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Webapi__Dom__Element from "bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Element.js";

function getCameras(param) {
  return window.navigator.mediaDevices.enumerateDevices().then((function (devices) {
                return Promise.resolve(Belt_Array.keep(devices, (function (x) {
                                  return x.kind === "videoinput";
                                })));
              }));
}

function getAudioStream(param) {
  return window.navigator.mediaDevices.getUserMedia({
              audio: true
            });
}

function initStreamByDeviceId(videoEl, deviceId) {
  return window.navigator.mediaDevices.getUserMedia({
                video: {
                  deviceId: deviceId
                }
              }).then((function (stream) {
                videoEl.srcObject = stream;
                var video = Webapi__Dom__Element.asHtmlElement(videoEl);
                if (video !== undefined) {
                  Caml_option.valFromOption(video).setAttribute("playsinline", "true");
                }
                videoEl.play();
                return Promise.resolve(videoEl);
              }));
}

export {
  getCameras ,
  getAudioStream ,
  initStreamByDeviceId ,
  
}
/* Webapi__Dom__Element Not a pure module */
