// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Webapi__Dom__Element = require("bs-webapi/src/Webapi/Webapi__Dom/Webapi__Dom__Element.js");

function getCameras(param) {
  return window.navigator.mediaDevices.enumerateDevices().then((function (devices) {
                return Promise.resolve(Belt_Array.keep(devices, (function (x) {
                                  return x.kind === "videoinput";
                                })));
              }));
}

function getAudioStream(param) {
  return window.navigator.mediaDevices.getUserMedia({
              audio: true
            });
}

function initStreamByDeviceId(videoEl, deviceId) {
  return window.navigator.mediaDevices.getUserMedia({
                video: {
                  deviceId: deviceId
                }
              }).then((function (stream) {
                videoEl.srcObject = stream;
                var video = Webapi__Dom__Element.asHtmlElement(videoEl);
                if (video !== undefined) {
                  Caml_option.valFromOption(video).setAttribute("playsinline", "true");
                }
                videoEl.play();
                return Promise.resolve(videoEl);
              }));
}

exports.getCameras = getCameras;
exports.getAudioStream = getAudioStream;
exports.initStreamByDeviceId = initStreamByDeviceId;
/* Webapi__Dom__Element Not a pure module */
