// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var ElementRe = require("bs-webapi/src/dom/nodes/ElementRe.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function withQuerySelector(query, f) {
  return Belt_Option.map(Belt_Option.flatMap(Caml_option.nullable_to_opt(document.querySelector(query)), ElementRe.asHtmlElement), f);
}

function withQuerySelectorAll(query, f) {
  return $$Array.map(f, Array.prototype.slice.call(document.querySelectorAll(query)));
}

exports.withQuerySelector = withQuerySelector;
exports.withQuerySelectorAll = withQuerySelectorAll;
/* ElementRe Not a pure module */
