// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";
import * as Color$QueerLoop from "../src/Color.bs.js";

Jest.describe("Color", (function (param) {
        Jest.describe("rgbToHsv", (function (param) {
                return Jest.testAll("in => out", /* :: */[
                            /* tuple */[
                              /* tuple */[
                                1.0,
                                1.0,
                                1.0
                              ],
                              /* tuple */[
                                0.0,
                                0.0,
                                1.0
                              ]
                            ],
                            /* :: */[
                              /* tuple */[
                                /* tuple */[
                                  1.0,
                                  0.0,
                                  0.0
                                ],
                                /* tuple */[
                                  0.0,
                                  1.0,
                                  1.0
                                ]
                              ],
                              /* :: */[
                                /* tuple */[
                                  /* tuple */[
                                    0.0,
                                    1.0,
                                    0.0
                                  ],
                                  /* tuple */[
                                    1.0 / 3.0,
                                    1.0,
                                    1.0
                                  ]
                                ],
                                /* [] */0
                              ]
                            ]
                          ], (function (param) {
                              var match = param[0];
                              return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Color$QueerLoop.rgbToHsv(match[0], match[1], match[2])));
                            }));
              }));
        Jest.describe("hsvToRgb", (function (param) {
                return Jest.testAll("in => out", /* :: */[
                            /* tuple */[
                              /* tuple */[
                                0.0,
                                1.0,
                                1.0
                              ],
                              /* tuple */[
                                1.0,
                                0.0,
                                0.0
                              ]
                            ],
                            /* :: */[
                              /* tuple */[
                                /* tuple */[
                                  0.0,
                                  0.0,
                                  1.0
                                ],
                                /* tuple */[
                                  1.0,
                                  1.0,
                                  1.0
                                ]
                              ],
                              /* :: */[
                                /* tuple */[
                                  /* tuple */[
                                    0.0,
                                    0.2,
                                    1.0
                                  ],
                                  /* tuple */[
                                    1.0,
                                    0.8,
                                    0.8
                                  ]
                                ],
                                /* :: */[
                                  /* tuple */[
                                    /* tuple */[
                                      1.0 / 3.0,
                                      1.0,
                                      1.0
                                    ],
                                    /* tuple */[
                                      0.0,
                                      1.0,
                                      0.0
                                    ]
                                  ],
                                  /* [] */0
                                ]
                              ]
                            ]
                          ], (function (param) {
                              var match = param[0];
                              return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Color$QueerLoop.hsvToRgb(match[0], match[1], match[2])));
                            }));
              }));
        Jest.describe("getNextColor", (function (param) {
                return Jest.testAll("in => out", /* :: */[
                            /* tuple */[
                              "#fff",
                              "#fcc"
                            ],
                            /* :: */[
                              /* tuple */[
                                "#fcc",
                                "#ffc"
                              ],
                              /* :: */[
                                /* tuple */[
                                  "#ffc",
                                  "#cfc"
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "#000",
                                    "#fff"
                                  ],
                                  /* [] */0
                                ]
                              ]
                            ]
                          ], (function (param) {
                              return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Color$QueerLoop.getNextColor(param[0])));
                            }));
              }));
        return Jest.describe("getNextHsv", (function (param) {
                      return Jest.testAll("in => out", /* :: */[
                                  /* tuple */[
                                    /* tuple */[
                                      0.0,
                                      0.0,
                                      1.0
                                    ],
                                    /* tuple */[
                                      0.0,
                                      0.2,
                                      1.0
                                    ]
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      /* tuple */[
                                        0.0,
                                        0.2,
                                        1.0
                                      ],
                                      /* tuple */[
                                        0.2,
                                        0.2,
                                        1.0
                                      ]
                                    ],
                                    /* :: */[
                                      /* tuple */[
                                        /* tuple */[
                                          0.2,
                                          0.2,
                                          1.0
                                        ],
                                        /* tuple */[
                                          0.4,
                                          0.2,
                                          1.0
                                        ]
                                      ],
                                      /* :: */[
                                        /* tuple */[
                                          /* tuple */[
                                            0.6,
                                            0.2,
                                            1.0
                                          ],
                                          /* tuple */[
                                            0.8,
                                            0.2,
                                            1.0
                                          ]
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            /* tuple */[
                                              0.8,
                                              0.2,
                                              1.0
                                            ],
                                            /* tuple */[
                                              0.0,
                                              0.4,
                                              1.0
                                            ]
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              /* tuple */[
                                                0.8,
                                                0.8,
                                                1.0
                                              ],
                                              /* tuple */[
                                                0.0,
                                                1.0,
                                                1.0
                                              ]
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                /* tuple */[
                                                  0.0,
                                                  1.0,
                                                  1.0
                                                ],
                                                /* tuple */[
                                                  0.2,
                                                  1.0,
                                                  1.0
                                                ]
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  /* tuple */[
                                                    0.8,
                                                    1.0,
                                                    1.0
                                                  ],
                                                  /* tuple */[
                                                    0.0,
                                                    0.0,
                                                    0.8
                                                  ]
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    /* tuple */[
                                                      0.8,
                                                      1.0,
                                                      0.4
                                                    ],
                                                    /* tuple */[
                                                      0.0,
                                                      0.0,
                                                      0.2
                                                    ]
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      /* tuple */[
                                                        0.0,
                                                        0.0,
                                                        0.2
                                                      ],
                                                      /* tuple */[
                                                        0.0,
                                                        0.0,
                                                        0.0
                                                      ]
                                                    ],
                                                    /* :: */[
                                                      /* tuple */[
                                                        /* tuple */[
                                                          0.0,
                                                          0.0,
                                                          0.0
                                                        ],
                                                        /* tuple */[
                                                          0.0,
                                                          0.0,
                                                          1.0
                                                        ]
                                                      ],
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ], (function (param) {
                                    return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Color$QueerLoop.getNextHsv(param[0])));
                                  }));
                    }));
      }));

export {
  
}
/*  Not a pure module */
