// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var IndexedDB$QueerLoop = require("../src/IndexedDB.bs.js");

Jest.describe("open", (function (param) {
        return Jest.test("opens a connection to the database", (function (param) {
                      var request = function (param, param$1) {
                        return IndexedDB$QueerLoop.DB.open_("test", 1, param, param$1);
                      };
                      return Jest.ExpectJs.toBeTruthy(Jest.ExpectJs.expect(request));
                    }));
      }));

/*  Not a pure module */
