// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";
import * as QrCodeGen$QueerLoop from "../src/QrCodeGen.bs.js";
import * as QueerCode$QueerLoop from "../src/QueerCode.bs.js";

var qrCode = QrCodeGen$QueerLoop.QrCode._encodeText("https://qqq.lu", QrCodeGen$QueerLoop.Ecc.low);

Jest.describe("QueerCode", (function (param) {
        Jest.Only.describe("createSimpleSvg", (function (param) {
                return Jest.test("translates QR code data into QueerCode SVG", (function (param) {
                              return Jest.Expect.toEqual("", Jest.Expect.expect(""));
                            }));
              }));
        return Jest.describe("drawCanvas", (function (param) {
                      return Jest.test("applies a QueerCode to a canvas", (function (param) {
                                    var canvas = document.createElement("canvas");
                                    QueerCode$QueerLoop.drawCanvas(canvas, qrCode);
                                    canvas.toDataURL();
                                    return Jest.Expect.toEqual("", Jest.Expect.expect(canvas.toDataURL()));
                                  }));
                    }));
      }));

export {
  qrCode ,
  
}
/* qrCode Not a pure module */
