// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var QrCodeGen$QueerLoop = require("../src/QrCodeGen.bs.js");
var QueerCode$QueerLoop = require("../src/QueerCode.bs.js");

var qrCode = QrCodeGen$QueerLoop.QrCode._encodeText("https://qqq.lu", QrCodeGen$QueerLoop.Ecc.low);

Jest.describe("QueerCode", (function (param) {
        Jest.Only.describe("createSimpleSvg", (function (param) {
                return Jest.test("translates QR code data into QueerCode SVG", (function (param) {
                              return Jest.Expect.toEqual("", Jest.Expect.expect(""));
                            }));
              }));
        return Jest.describe("drawCanvas", (function (param) {
                      return Jest.test("applies a QueerCode to a canvas", (function (param) {
                                    var canvas = document.createElement("canvas");
                                    QueerCode$QueerLoop.drawCanvas(canvas, qrCode);
                                    canvas.toDataURL();
                                    return Jest.Expect.toEqual("", Jest.Expect.expect(canvas.toDataURL()));
                                  }));
                    }));
      }));

exports.qrCode = qrCode;
/* qrCode Not a pure module */
